binary: true
tiers_lst:
- '1'
pheno_category_lst:
- WHO
amb_mode: DROP
pool_lof: true
pool_inframe: false
synonymous: false
AF_thresh: 0.75
missing_isolate_thresh: 0.01
missing_feature_thresh: 0.25
drop_isolates_before_variants: false
impute: false
num_PCs: 5
num_bootstrap: 1000
alpha: 0.05