tiers_lst: ['1']
drug: 'Moxifloxacin'
drug_WHO_abbr: 'MXF'
out_dir: '/n/data1/hms/dbmi/farhat/ye12/who/analysis/Drugs'
model_prefix: 'tiers=1_drop_HET'

# model input processing
missing_thresh: 0.01
het_mode: "DROP"
AF_thresh: 0.75
impute: False
include_synonymous: False

# analysis
# filtering threshold for computing the genetic relatedness matrix 
MAF: 0.01
num_PCs: 5
num_bootstrap: 1000
alpha: 0.05