drug: 'Rifampicin'
drug_WHO_abbr: 'RIF'
tiers_lst: ['1', '2']
pheno_category_lst: ['WHO', 'ALL']
model_prefix: 'dropHET_noSyn_noPopCorr'

missing_isolate_thresh: 0.01
missing_feature_thresh: 0.25
het_mode: "DROP"
AF_thresh: 0.75
drop_isolates_before_variants: False
impute: False
synonymous: False
pool_lof: False

num_PCs: 0
num_bootstrap: 1000
alpha: 0.05